version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      quality-toolchain:
        patterns:
          - "ruff"
          - "pylint"
          - "mypy"
          - "pyright"
          - "tox"
          - "black"
          - "build"
          - "pre-commit"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
