"""Morpion neural-network evaluator helpers."""

from __future__ import annotations

from typing import Any

__all__ = [
    "DEFAULT_MORPION_FEATURE_SUBSET_NAME",
    "HANDCRAFTED_5_CORE_FEATURE_NAMES",
    "HANDCRAFTED_10_CORE_FEATURE_NAMES",
    "HANDCRAFTED_20_CORE_FEATURE_NAMES",
    "MORPION_BUILTIN_FEATURE_SUBSET_NAMES",
    "MORPION_CANONICAL_FEATURE_NAMES",
    "MORPION_ENTITY_RELATION_SCHEMA",
    "MORPION_ENTITY_RELATION_TYPE_COUNT",
    "MORPION_ENTITY_TOKEN_DIRECTIONS",
    "MORPION_ENTITY_TOKEN_FEATURE_DIM",
    "MORPION_ENTITY_TOKEN_FEATURE_NAMES",
    "MORPION_ENTITY_TOKEN_INPUT_REPRESENTATION",
    "MORPION_ENTITY_TOKEN_MODEL_KIND",
    "MORPION_FEATURE_SCHEMA",
    "MORPION_INPUT_DIM",
    "MORPION_MANIFEST_FILE_NAME",
    "MORPION_MODEL_ARGS_FILE_NAME",
    "MORPION_MODEL_READABLE_WEIGHTS_FILE_NAME",
    "MORPION_MODEL_WEIGHTS_FILE_NAME",
    "MORPION_RELATION_BIASED_ENTITY_TOKEN_MODEL_KIND",
    "CandidateSegment",
    "IncompatibleMorpionModelBundleError",
    "InconsistentMorpionFeatureSubsetDefinitionError",
    "InvalidMorpionFeatureSubsetError",
    "InvalidMorpionModelBundleError",
    "MissingMorpionHiddenDimError",
    "MissingMorpionHiddenSizesError",
    "MorpionEntityRelationType",
    "MorpionEntityTokenConverter",
    "MorpionEntityTokenLayout",
    "MorpionEntityTokenType",
    "MorpionFeatureSchema",
    "MorpionFeatureSubset",
    "MorpionFeatureTensorConverter",
    "MorpionModelManifest",
    "MorpionNNInput",
    "MorpionRegressor",
    "MorpionRegressorArgs",
    "MorpionRelationalEntityTokenConverter",
    "MorpionRelationalEntityTokens",
    "UnknownMorpionFeatureSubsetError",
    "UnsupportedMorpionModelKindError",
    "build_morpion_nn_input",
    "build_morpion_regressor",
    "canonical_segment",
    "extract_morpion_features",
    "full_morpion_feature_schema",
    "full_morpion_feature_subset",
    "is_morpion_entity_token_model_kind",
    "is_relational_entity_token_model_kind",
    "load_morpion_model_bundle",
    "load_morpion_regressor_for_inference",
    "morpion_feature_names",
    "morpion_feature_subset_from_feature_names",
    "morpion_feature_subset_from_name",
    "morpion_input_dim",
    "morpion_state_to_tensor",
    "resolve_morpion_feature_subset",
    "save_morpion_model_bundle",
    "subset_indices",
    "validate_morpion_feature_subset",
]

_EXPORT_MODULES = {
    "DEFAULT_MORPION_FEATURE_SUBSET_NAME": ".feature_schema",
    "HANDCRAFTED_5_CORE_FEATURE_NAMES": ".feature_schema",
    "HANDCRAFTED_10_CORE_FEATURE_NAMES": ".feature_schema",
    "HANDCRAFTED_20_CORE_FEATURE_NAMES": ".feature_schema",
    "MORPION_BUILTIN_FEATURE_SUBSET_NAMES": ".feature_schema",
    "MORPION_CANONICAL_FEATURE_NAMES": ".feature_schema",
    "MORPION_FEATURE_SCHEMA": ".feature_schema",
    "MORPION_ENTITY_TOKEN_DIRECTIONS": ".entity_tokens",
    "MORPION_ENTITY_TOKEN_INPUT_REPRESENTATION": ".entity_tokens",
    "MORPION_ENTITY_TOKEN_MODEL_KIND": ".entity_tokens",
    "MORPION_ENTITY_TOKEN_FEATURE_DIM": ".entity_tokens",
    "MORPION_ENTITY_TOKEN_FEATURE_NAMES": ".entity_tokens",
    "MORPION_ENTITY_RELATION_SCHEMA": ".entity_relations",
    "MORPION_ENTITY_RELATION_TYPE_COUNT": ".entity_relations",
    "MORPION_RELATION_BIASED_ENTITY_TOKEN_MODEL_KIND": ".entity_relations",
    "MORPION_INPUT_DIM": ".model",
    "MORPION_MANIFEST_FILE_NAME": ".bundle",
    "MORPION_MODEL_ARGS_FILE_NAME": ".bundle",
    "MORPION_MODEL_READABLE_WEIGHTS_FILE_NAME": ".bundle",
    "MORPION_MODEL_WEIGHTS_FILE_NAME": ".bundle",
    "CandidateSegment": ".feature_extractor",
    "IncompatibleMorpionModelBundleError": ".bundle",
    "InconsistentMorpionFeatureSubsetDefinitionError": ".feature_schema",
    "InvalidMorpionFeatureSubsetError": ".feature_schema",
    "InvalidMorpionModelBundleError": ".bundle",
    "MissingMorpionHiddenDimError": ".model",
    "MissingMorpionHiddenSizesError": ".model",
    "MorpionFeatureSchema": ".feature_schema",
    "MorpionFeatureSubset": ".feature_schema",
    "MorpionFeatureTensorConverter": ".state_to_tensor",
    "MorpionEntityTokenConverter": ".entity_tokens",
    "MorpionEntityTokenLayout": ".entity_tokens",
    "MorpionEntityTokenType": ".entity_tokens",
    "MorpionEntityRelationType": ".entity_relations",
    "MorpionRelationalEntityTokenConverter": ".entity_relations",
    "MorpionRelationalEntityTokens": ".entity_relations",
    "MorpionModelManifest": ".bundle",
    "MorpionNNInput": ".morpion_nn_input",
    "MorpionRegressor": ".model",
    "MorpionRegressorArgs": ".model",
    "UnknownMorpionFeatureSubsetError": ".feature_schema",
    "UnsupportedMorpionModelKindError": ".model",
    "build_morpion_nn_input": ".morpion_nn_input",
    "build_morpion_regressor": ".model",
    "canonical_segment": ".entity_tokens",
    "extract_morpion_features": ".feature_extractor",
    "full_morpion_feature_schema": ".feature_schema",
    "full_morpion_feature_subset": ".feature_schema",
    "is_morpion_entity_token_model_kind": ".entity_tokens",
    "is_relational_entity_token_model_kind": ".entity_relations",
    "load_morpion_model_bundle": ".bundle",
    "load_morpion_regressor_for_inference": ".bundle",
    "morpion_feature_names": ".feature_extractor",
    "morpion_feature_subset_from_feature_names": ".feature_schema",
    "morpion_feature_subset_from_name": ".feature_schema",
    "morpion_input_dim": ".state_to_tensor",
    "morpion_state_to_tensor": ".state_to_tensor",
    "resolve_morpion_feature_subset": ".feature_schema",
    "save_morpion_model_bundle": ".bundle",
    "subset_indices": ".feature_schema",
    "validate_morpion_feature_subset": ".feature_schema",
}


def __getattr__(name: str) -> Any:
    """Resolve public helpers lazily so schema imports stay dependency-light."""
    try:
        module_name = _EXPORT_MODULES[name]
    except KeyError as exc:
        raise AttributeError(name) from exc

    from importlib import import_module

    value = getattr(import_module(module_name, __name__), name)
    globals()[name] = value
    return value
