"""Original-code golden evidence for the opt-in historical graph representation."""

from __future__ import annotations

import hashlib
import json
from dataclasses import replace
from pathlib import Path

import pytest
import torch
from atomheart.games.morpion.checkpoints import MorpionStateCheckpointCodec

from chipiron.environments.morpion.learning import (
    MorpionSupervisedRow,
    save_morpion_supervised_rows_streaming,
)
from chipiron.environments.morpion.players.evaluators.neural_networks.bundle import (
    load_morpion_model_bundle,
    save_morpion_model_bundle,
)
from chipiron.environments.morpion.players.evaluators.neural_networks.legacy_graph.config import (
    LegacyGraphConfig,
    legacy_graph_config_from_dict,
)
from chipiron.environments.morpion.players.evaluators.neural_networks.legacy_graph.tokens import (
    MORPION_GRAPH_TOKEN_FEATURE_NAMES,
    MorpionGraphTokenConverter,
)
from chipiron.environments.morpion.players.evaluators.neural_networks.model import (
    MorpionRegressorArgs,
    build_morpion_regressor,
)
from chipiron.environments.morpion.players.evaluators.neural_networks.training import (
    MorpionStreamingTrainingArgs,
    MorpionTrainingArgs,
    train_morpion_regressor_streaming,
)
from chipiron.environments.morpion.players.evaluators.neural_networks.training.entity_token_cache import (
    load_or_materialize_entity_token_cache,
)
from chipiron.environments.morpion.types import MorpionDynamics

GOLDEN = json.loads(
    (Path(__file__).parents[1] / "data/morpion_legacy_graph_v1.json").read_text()
)


def _small_legacy() -> LegacyGraphConfig:
    return LegacyGraphConfig(
        graph_max_tokens=32,
        graph_d_model=8,
        graph_n_head=2,
        graph_n_layer=1,
        graph_dim_feedforward=16,
    )


@pytest.mark.parametrize(
    "case",
    GOLDEN["cases"],
    ids=lambda case: f"depth{case['depth']}-limit{case['max_tokens']}",
)
def test_legacy_tokens_and_forward_match_original_golden(case: dict) -> None:
    """Goldens were generated by original Chipiron and original Coral, not this layer."""
    assert list(MORPION_GRAPH_TOKEN_FEATURE_NAMES) == GOLDEN["feature_names"]
    atom = MorpionStateCheckpointCodec().load_state_ref(case["state_ref"])
    state = MorpionDynamics().wrap_atomheart_state(atom)
    tokens = MorpionGraphTokenConverter(max_tokens=case["max_tokens"]).state_to_tensor(
        state
    )
    assert list(tokens.shape) == case["shape"]
    assert hashlib.sha256(tokens.numpy().tobytes()).hexdigest() == case["token_sha256"]
    assert tokens[0, 0] == 1  # historical explicit VALUE token
    assert tokens[0, -1] == 1  # historical validity feature at index 25
    model = _small_legacy().build_model().eval()
    with torch.no_grad():
        for index, (_, parameter) in enumerate(model.named_parameters()):
            parameter.copy_(
                torch.sin(
                    torch.arange(parameter.numel(), dtype=torch.float32).reshape(
                        parameter.shape
                    )
                    + index
                )
                * 0.1
            )
        actual = model(tokens).flatten()
    torch.testing.assert_close(
        actual, torch.tensor(case["prediction"]), rtol=1e-6, atol=1e-6
    )
    assert (
        model.input_projection.in_features == 25
    )  # validity stripped; type_value retained
    assert model.value_token is not None  # preserve the additional learned Coral token


def test_legacy_bundle_roundtrip_and_historical_field_loading(tmp_path: Path) -> None:
    """Old fields and new explicit compatibility blocks load exactly the same weights."""
    args = MorpionRegressorArgs(
        model_kind="entity_token_transformer_value_net",
        legacy_graph_tokens=_small_legacy(),
    )
    model = build_morpion_regressor(args).eval()
    save_morpion_model_bundle(model, tmp_path, model_args=args)
    loaded, loaded_args, manifest = load_morpion_model_bundle(tmp_path)
    assert loaded_args == args
    assert manifest.input_representation == "graph_tokens_v1"
    file = tmp_path / "morpion_regressor_args.json"
    payload = json.loads(file.read_text())
    block = payload.pop("legacy_graph_tokens")
    block.pop("representation")
    payload.update(block)
    payload.pop("input_representation")  # original bundles omitted it in args
    file.write_text(json.dumps(payload))
    old_loaded, _, _ = load_morpion_model_bundle(tmp_path)
    for key, value in model.state_dict().items():
        assert torch.equal(loaded.state_dict()[key], value)
        assert torch.equal(old_loaded.state_dict()[key], value)
    (tmp_path / "param.pt").unlink()
    with pytest.raises(FileNotFoundError):
        load_morpion_model_bundle(tmp_path)


@pytest.mark.parametrize(
    "change",
    [
        {"graph_input_feature_dim": 25},
        {"representation": "morpion_entity_tokens_v1"},
        {"unknown": 1},
        {"graph_n_layer": True},
    ],
)
def test_legacy_config_rejects_schema_changes(change: dict) -> None:
    """Verify legacy config rejects schema changes."""
    with pytest.raises(ValueError):
        legacy_graph_config_from_dict({**_small_legacy().to_dict(), **change})


def test_legacy_cache_and_training_are_isolated_from_modern_tokens(
    tmp_path: Path,
) -> None:
    """Exercise actual streaming training, cache reuse, and portable bundle inference."""
    rows = tuple(
        MorpionSupervisedRow(
            node_id=str(i),
            state_ref_payload=case["state_ref"],
            target_value=float(i),
            is_terminal=False,
            is_exact=False,
            depth=case["depth"],
        )
        for i, case in enumerate(GOLDEN["cases"][::3])
    )
    path = tmp_path / "rows.jsonl"
    save_morpion_supervised_rows_streaming(rows=rows, path=path, metadata={})
    kwargs = dict(rows_path=path, row_chunk_size=2, max_rows=None, entity_max_tokens=32)
    modern = load_or_materialize_entity_token_cache(**kwargs)
    legacy = load_or_materialize_entity_token_cache(
        **kwargs, legacy_graph_tokens=_small_legacy()
    )
    assert legacy.paths != modern.paths
    assert legacy.manifest.input_representation == "graph_tokens_v1"
    assert legacy.packed_input_tensor.shape[1] == 26
    reused = load_or_materialize_entity_token_cache(
        **kwargs, legacy_graph_tokens=_small_legacy()
    )
    assert not reused.rebuilt
    assert torch.equal(legacy.packed_input_tensor, reused.packed_input_tensor)
    args = MorpionTrainingArgs(
        dataset_file=path,
        output_dir=tmp_path / "model",
        model_kind="entity_token_transformer_value_net",
        legacy_graph_tokens=_small_legacy(),
        num_epochs=1,
        batch_size=2,
        device="cpu",
    )
    _, metrics = train_morpion_regressor_streaming(
        MorpionStreamingTrainingArgs(training_args=args, row_chunk_size=2)
    )
    assert metrics["num_samples"] == 3
    _, loaded_args, manifest = load_morpion_model_bundle(args.output_dir)
    assert loaded_args.legacy_graph_tokens == _small_legacy()
    assert manifest.input_representation == "graph_tokens_v1"
    assert replace(loaded_args, legacy_graph_tokens=None).input_dim == 25
